# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `diff-lcs` gem.
# Please instead update this file by running `bin/tapioca gem diff-lcs`.

class Integer < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Integer
end
