# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mocha` gem.
# Please instead update this file by running `bin/tapioca gem mocha`.

module Mocha; end

class Mocha::BacktraceFilter
  def initialize(lib_directory = T.unsafe(nil)); end

  def filtered(backtrace); end
end

Mocha::BacktraceFilter::LIB_DIRECTORY = T.let(T.unsafe(nil), String)

class Mocha::Deprecation
  class << self
    def messages; end
    def messages=(_arg0); end
    def mode; end
    def mode=(_arg0); end
    def warning(*messages); end
  end
end

Mocha::RUBY_V2_PLUS = T.let(T.unsafe(nil), TrueClass)
Mocha::VERSION = T.let(T.unsafe(nil), String)
