inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'sorbet/**/*'
    - 'bin/**/*'
    - 'test/**/*'

Sorbet:
  Enabled: true
Sorbet/HasSigil:
  Enabled: true
  Exclude:
    - Gemfile*
Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - Gemfile*
Sorbet/ValidSigil:
  Enabled: true
Sorbet/EnforceSigilOrder:
  Enabled: true
Sorbet/AllowIncompatibleOverride:
  Enabled: true
Sorbet/CheckedTrueInSignature:
  Enabled: true
Sorbet/KeywordArgumentOrdering:
  Enabled: true
Sorbet/ParametersOrderingInSignature:
  Enabled: true
Sorbet/SignatureBuildOrder:
  Enabled: true
Sorbet/BindingConstantWithoutTypeAlias:
  Enabled: true
Sorbet/ConstantsFromStrings:
  Enabled: true
Sorbet/ForbidIncludeConstLiteral:
  Enabled: true
Sorbet/ForbidSuperclassConstLiteral:
  Enabled: true