version: '3.5'
services:
  api:
    container_name: shopify_api
    image: ruby:2.6
    working_dir: /shopify_api
    volumes:
      - .:/shopify_api
      - bundle:/usr/local/bundle
    command: bash -c "bundle install && tail -f /dev/null"

volumes:
  bundle:
